# Generated by Django 3.1 on 2021-02-05 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210205_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=256)),
                ('address_line_2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=56)),
                ('postcode', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CharityAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityname', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiertaryRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_halal', models.BooleanField(default=False)),
                ('has_sanitary_products', models.BooleanField(default=False)),
                ('has_vegetarian', models.BooleanField(default=False)),
                ('has_vegan', models.BooleanField(default=False)),
                ('has_kosher', models.BooleanField(default=False)),
                ('has_gluten_free', models.BooleanField(default=False)),
                ('has_lactose_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDietaryPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diertaryrequirements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharityDietaryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.charityaccount')),
                ('dietary_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diertaryrequirements')),
            ],
        ),
    ]
